export const listingData = [
  {
    id: "1",
    name: "John Doe",
    type: "Type",
    seller_name: "Femi Omoseni",
    date: "25th October 2024",
    price: 50,
    location: "Magboro",
    status: "Rejected",
  },
  {
    id: "1",
    name: "John Doe",
    type: "Type",
    seller_name: "Femi Omoseni",
    date: "25th October 2024",
    price: 50,
    location: "Magboro",
    status: "Rejected",
  },
  {
    id: "1",
    name: "John Doe",
    type: "Type",
    seller_name: "Femi Omoseni",
    date: "25th October 2024",
    price: 50,
    location: "Magboro",
    status: "Rejected",
  },
  {
    id: "1",
    name: "John Doe",
    type: "Type",
    seller_name: "Femi Omoseni",
    date: "25th October 2024",
    price: 50,
    location: "Magboro",
    status: "Rejected",
  },
  {
    id: "1",
    name: "John Doe",
    type: "Type",
    seller_name: "Femi Omoseni",
    date: "25th October 2024",
    price: 50,
    location: "Magboro",
    status: "Approved",
  },
  {
    id: "1",
    name: "John Doe",
    type: "Type",
    seller_name: "Femi Omoseni",
    date: "25th October 2024",
    price: 50,
    location: "Magboro",
    status: "Approved",
  },
  {
    id: "1",
    name: "John Doe",
    type: "Type",
    seller_name: "Femi Omoseni",
    date: "25th October 2024",
    price: 50,
    location: "Magboro",
    status: "Pending",
  },
  {
    id: "1",
    name: "John Doe",
    type: "Type",
    seller_name: "Femi Omoseni",
    date: "25th October 2024",
    price: 50,
    location: "Magboro",
    status: "Pending",
  },
  {
    id: "1",
    name: "John Doe",
    type: "Type",
    seller_name: "Femi Omoseni",
    date: "25th October 2024",
    price: 50,
    location: "Magboro",
    status: "Pending",
  },
  {
    id: "1",
    name: "John Doe",
    type: "Type",
    seller_name: "Femi Omoseni",
    date: "25th October 2024",
    price: 50,
    location: "Magboro",
    status: "Pending",
  },
  {
    id: "1",
    name: "John Doe",
    type: "Type",
    seller_name: "Femi Omoseni",
    date: "25th October 2024",
    price: 50,
    location: "Magboro",
    status: "Pending",
  },
  {
    id: "1",
    name: "John Doe",
    type: "Type",
    seller_name: "Femi Omoseni",
    date: "25th October 2024",
    price: 50,
    location: "Magboro",
    status: "Approved",
  },
  {
    id: "1",
    name: "John Doe",
    type: "Type",
    seller_name: "Femi Omoseni",
    date: "25th October 2024",
    price: 50,
    location: "Magboro",
    status: "Approved",
  },
  {
    id: "1",
    name: "John Doe",
    type: "Type",
    seller_name: "Femi Omoseni",
    date: "25th October 2024",
    price: 50,
    location: "Magboro",
    status: "Approved",
  },
];

export const topPerformers = [
  {
    id: "1",
    name: "John Doe",
    location: "Magboro",
    inquiries: "some Desc",
    views: 100,
  },
  {
    id: "1",
    name: "John Doe",
    location: "Magboro",
    inquiries: "some Desc",
    views: 100,
  },
  {
    id: "1",
    name: "John Doe",
    location: "Magboro",
    inquiries: "some Desc",
    views: 100,
  },
  {
    id: "1",
    name: "John Doe",
    location: "Magboro",
    inquiries: "some Desc",
    views: 100,
  },
  {
    id: "1",
    name: "John Doe",
    location: "Magboro",
    inquiries: "some Desc",
    views: 100,
  },
  {
    id: "1",
    name: "John Doe",
    location: "Magboro",
    inquiries: "some Desc",
    views: 100,
  },
  {
    id: "1",
    name: "John Doe",
    location: "Magboro",
    inquiries: "some Desc",
    views: 100,
  },
  {
    id: "1",
    name: "John Doe",
    location: "Magboro",
    inquiries: "some Desc",
    views: 100,
  },
];

export const propertyData = [
  {
    id: "1",
    name: "John Doe",
    location: "Lagos",
    inquiries: "25",
    views: "10,000",
  },
  {
    id: "1",
    name: "John Doe",
    location: "Lagos",
    inquiries: "25",
    views: "10,000",
  },
];

export const categoryData = [
  {
    id: "1",
    name: "Houses",
    subCategoryCount: "23",
  },
  {
    id: "1",
    name: "Land",
    subCategoryCount: "13",
  },
  {
    id: "1",
    name: "Automobile",
    subCategoryCount: "19",
  },
];

export const subCategoryData = [
  {
    id: "1",
    name: "Hatchbacks",
  },
  {
    id: "1",
    name: "SUVs",
  },
  {
    id: "1",
    name: "Sedans",
  },
];

export const complaintData = [
  {
    id: 1,
    name: "John Doe",
    category: "Property Listing",
    complaint_details: "Listing contains false information",
    date: "Oct 14, 2024",
    status: "Open",
  },
  {
    id: 1,
    name: "John Doe",
    category: "Property Listing",
    complaint_details: "Listing contains false information",
    date: "Oct 14, 2024",
    status: "Open",
  },
  {
    id: 1,
    name: "John Doe",
    category: "Property Listing",
    complaint_details: "Listing contains false information",
    date: "Oct 14, 2024",
    status: "Open",
  },
  {
    id: 1,
    name: "John Doe",
    category: "Property Listing",
    complaint_details: "Listing contains false information",
    date: "Oct 14, 2024",
    status: "Pending",
  },
  {
    id: 1,
    name: "John Doe",
    category: "Property Listing",
    complaint_details: "Listing contains false information",
    date: "Oct 14, 2024",
    status: "Escalated",
  },
  {
    id: 1,
    name: "John Doe",
    category: "Property Listing",
    complaint_details: "Listing contains false information",
    date: "Oct 14, 2024",
    status: "Resolved",
  },
];
